### ISSUE TITLE
Add a 'branch' information

### ISSUE THREAD

**Issue by cdevienne** [influxdata/grade#1]
Knowing the branch on which the bench were run could be interesting.
It may help deciding if a feature branch can be merge for example.
It can also help to see the evolution of each branch over time.

Not knowing well influxDB, I don't know if it should be a tag or a field.

**Comment by mark-rushakoff** [comment]
Seems like it would be useful. I'm going to tag this as "help wanted" until I'm able to make the time to address it.

* Should be a new, optional command line flag `branch`
  * If supplied, is a new tag on the output data (so you can group by it)
  * If omitted, is not a tag on the output data (maintaining backwards compatibility)
* README will need to be updated
